global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
  -   job_name: "client-service"
      metrics_path: /actuator/prometheus
      static_configs:
        - targets: [client-service:8095]
  -   job_name: "oil-service"
      metrics_path: /actuator/prometheus
      static_configs:
        - targets: [oil-service:8096]
  -   job_name: "car-service"
      metrics_path: /actuator/prometheus
      static_configs:
        - targets: [car-service:8097]
  -   job_name: "serv-service"
      metrics_path: /actuator/prometheus
      static_configs:
        - targets: [serv-service:8098]

