services:
  user-service:
    build:
      context: C:\git\ot\Java-Advanced-11-homework\gusarov\prometheus\
      dockerfile: Dockerfile
    hostname: user-service
    container_name: user-service
    restart: "no"
    ports:
      - 8095:8095
    networks:
      - t15net
    environment:
      AUTH: false

  prometheus:
    image: prom/prometheus
    depends_on:
      - user-service
    container_name: prometheus
    ports:
      - 9090:9090
    networks:
      - t15net
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always
    hostname: prometheus

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    networks:
      - t15net
    restart: always

networks:
  t15net:
    driver: bridge